### ISSUE TITLE
API site is down

### ISSUE THREAD

**Issue by jmatsushita** [hadolint/hadolint#107] opened 2017-11-07 09:38 UTC
Hi there,

It seems that I can't reach the API backend:

![image](https://user-images.githubusercontent.com/356097/32486704-bd9981dc-c3a7-11e7-8c80-dabf744f0e50.png)

Cheers,

Jun

**Comment by stefan2904** [comment] 2018-01-02 17:16
Using Firefox 57 I get:

```
Cross-Origin Request Blocked: 
The Same Origin Policy disallows reading the remote resource 
at http://api.hadolint.lukasmartinelli.ch/dockerfile. 
(Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
```

**Comment by lukasmartinelli** [comment] 2018-01-02 18:42
I shut down the server for the API site.

**Comment by PatMyron** [comment] 2019-05-11 22:09
duplicate of https://github.com/hadolint/hadolint/issues/75

**Comment by lorenzo** [comment] 2019-05-23 11:24
Closing as this is a duplicate

**Closed by lorenzo** 2019-05-23 11:24 UTC
